class Errors:
    error = {
        '-1': "NO estan las fechas correctas",
        '-2': "Este correo ya está en uso",
        '-3': "Este correo no es válido",
        '-4': "NO se encontro una cuenta asociada",
        '-6': "NO hay una cuenta con ese id",
        '-7': "No se encuentra el roool",
        '-8': "No se encuentra a la persona",
        '-9': "No hay personas censadas",
        '-10': "La fecha de fin debe ser posterior a la de inicio",
        '-11': "No existe la persona",
        '-12': "No existe el sensor solicitado",
        '-13': "No existe cuenta",
        '-16': "La direccion IP no es valida",
        '-14': "No tiene el token",
        '-15': "Token no valido",
        '-18': "Ingrese latitud y longitud validas",
        "-40": "No se encuentra",
        "-41": "Correo repetido",
        "-42": "DNI repetido",
        "-42": "Longitud de DNI mayor a 10",
        "-43": "La contraseña no coincide con la actual",
    }
